{% set name = "pprintpp" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea826108e2c7f49dc6d66c752973c3fc9749142a798d6b254e1e301cfdbc6403
  patches:
    - 0001-setup.py-Do-not-use-deprecated-U-mode.patch

build:
  noarch: python
  number: 6
  script: "{{ PYTHON }} -m pip install . -vv"

  entry_points:
    - pypprint = pprintpp:console

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pprintpp
  commands:
    - "echo \"{'hello': 'world'}\" | pypprint"  # [unix]

about:
  home: https://github.com/wolever/pprintpp
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "pprint++: a drop-in replacement for pprint that's actually pretty"
  dev_url: https://github.com/wolever/pprintpp

extra:
  recipe-maintainers:
    - scopatz
    - synapticarbors
