{% set name = "pprintpp" %}
{% set version = "0.4.0" %}
{% set sha256 = "ea826108e2c7f49dc6d66c752973c3fc9749142a798d6b254e1e301cfdbc6403" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - pypprint = pprintpp:console

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pprintpp
  commands:
    - "echo \"{'hello': 'world'}\" | pypprint"  # [unix]

about:
  home: https://github.com/wolever/pprintpp
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "pprint++: a drop-in replacement for pprint that's actually pretty"
  dev_url: https://github.com/wolever/pprintpp

extra:
  recipe-maintainers:
    - scopatz
